#!/bin/bash
if [ -e "/usr/share/terminfo/72/rxvt-unicode" ]
then
    echo ""
else 
    if [ -x "/usr/bin/tic" ]
    then 
        /usr/bin/tic /usr/local/poy4/urxvt/bin/etc/rxvt-unicode.terminfo
    fi
fi

cp -r '/usr/local/poy4/poy/bin/POY4 Beta Parallel.app' /Applications/
cp -r '/usr/local/poy4/poy/bin/POY4 Beta.app' /Applications/
cp -r /usr/local/poy4/poy/bin/cores_macosx.app /Applications/
open -a cores_macosx
cp /tmp/cores /usr/local/poy4/poy/bin/cores
echo 'export PATH=/usr/local/poy4/poy/bin:$PATH' >> $HOME/.bashrc
rm -fr /Applications/cores_macosx.app
